[tool.ruff]
line-length = 88 # Ruff's default line length is 88
extend-exclude = ["*.ipynb", "**/migrations/*"]

[tool.ruff.format]
quote-style = "single" # Ruff's default is double quotes, Django prefers single quotes

[tool.ruff.lint.per-file-ignores]
"sentio/settings/*.py" = ["F401", "F403", "F405"]

[tool.pytest.ini_options] # pytest configuration
DJANGO_SETTINGS_MODULE = "sentio.settings.testing"
python_files = ["test_*.py", "tests.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
pythonpath = ["."]
testpaths = ["ml_pipeline", "apps", "tests"]
markers = [
    "integration: marks tests as integration tests",
]

addopts = ["-v"]