# Author: Lian Shi
# This file is google secret service account

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentio-sa
  namespace: sentio
  annotations:
    iam.gke.io/gcp-service-account: sentio-secrets-sa@sentio1.iam.gserviceaccount.com
